# -*- coding: utf-8 -*-
"""12/26.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TCDB7jhnG7Vsf8eEyG8ZldwiYxgsBnkD
"""

n=0
while n<10:
  n=n+1
  print("n is",n)
  if n==4:
    break
print("Finished")

answer="123"
while True:
  password=input("Enter your password")
  if password==answer:
    print("Correct")
    break
  else:
    print("Fail,Try again")

answer1="123"
answer2="456"
while True:
  n1=input("Enter your password:")
  n2=input("Enter your account:")
  if n1==answer1 and n2==answer2:
    print("Account and Password Correct")
    break
  else:
    print("Fall,Try again")

answer1="a123456"
x=3
while True:
  n1=input("Enter your password,you have 3 chances")
  if n1==answer1:
    print("Correct")
    break
  else:
    x=x-1
    print("Fall,you have",x,"chances")
  if x==0:
    print("you fail")
    break

for a in range(6):
  print(a,end=" ")
print("")

sum=0
for x in range(1,11,2):
  sum=sum+x
print("1+3+5+7+9=",sum)