# -*- coding: utf-8 -*-
"""week4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CrUtTmoT8YOUqNVr4wUTSFNS6dgQoKUd
"""

print(a)

a=1
a

a="python"
a

a

print(a,id(a))

x=1
y=2
id(x)

id(y)

z=1
id(z)

0.1+0.1+0.1

bool(1)

bool(0)

a=123
b=123.456
c="python"

print(a)

a=123
b=123.456
c="python"

print(a)
print("a=",a)

print(a,end="   ")

print("123\t456")

s=input()

a=input("ENTER YOUR NAME")

a=int(input("ENTER YOUR NUMBER"))

a+1

#woovoovuuwawaaw

x=1
y=(1,2,3)
打印(y中的x)