# -*- coding: utf-8 -*-
"""week3-A108260084-葉則沅.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R0u8uNYA1kwQXrPd57Qm1Qz0_9qvwwQm
"""

print("hello world")

print("我是葉則沅")