# -*- coding: utf-8 -*-
"""重複迴圈4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1awXvLVLXfKXCsT6-6-SBm7AnKV1Fcs5L
"""

a = range(5)
print(a)
print(a[0], a[1], a[2], a[3], a[4])

b = range(2, 6)
print(b[0], b[1], b[2], b[3])

c = range(0, 6, 2)
print(c[0], c[1], c[2])

d = range(6, 0, -2)
print(d[0], d[1], d[2])

#range通常和for迴圈搭配, for i in range
for i in range(5):
 print(i)

for i in range(3):
 print("hi")

import random
for i in range(10):
 r = random.randint(1,100)
 print(r)

for i in range(100):
 r = random.randint(1,1000)
 print("第", i, "個隨機變數的值是", r)
t = 0

for i in range(100):
 t += 50
 print("第", i, "個數是", t )

for a in range(6):
 print(a, end =" ")
print("")

for b in range(1, 6, 2):
 print(b, end =" ")
print("")

for c in range(2, 6):
 print(c, end =" ")
print("")

for d in range(6, 1, -2):
 print(d, end =" ")

s = int(input('請輸入加總開始值?'))
e = int(input('請輸入加總終止值?'))
inc = int(input('請輸入遞增減值?'))
sum = 0 #初始結果
for i in range(s, e, inc): #判斷條件
 sum = sum + i #更新結果
 print('i為', i, '加總結果為', sum)

sum = 0
for x in range(1, 11, 2):
 sum = sum + x
print("1+3+5+7+9=", sum)

for a in range(6):
 print(a, end=" ")
print("")

for b in range(1, 6, 2):
 print(b, end=" ")
print("")

for c in range(2, 6):
 print(c, end=" ")
print("")

for d in range(6, 1, -2):
 print(d, end=" ")
print("")

n = int(input('請輸入n值?'))
sum = 0;
for i in range(1,n+1):
 sum = sum + i*i;
print(sum)

a = int(input("請輸入第1個數字:"))
b = int(input("請輸入第2個數字:"))
for c in range(a, 1, -1):
 if (a % c == 0 and b % c == 0):
  break
print("最大公約數 GCD =", c)
for c in range(a, a * b):
 if (c % a == 0 and c % b == 0):
  break
print("最小公倍數 LCM =", c)

num = int(input('輸入求第幾項費氏數列?'))
a = 1
b = 1
print(1,a)
for i in range(2, num+1):
 a, b = b, a+b
 print(i, a)

import random
while True:
 dice = random.randint(1,6)
 print(dice)
 if dice == 6:
  break